server:
  port: 8083

spring :
  data :
    mongodb :
      host : localhost
      port : 27017
      database : sample
      repositories :
        enabled : true
      username : ausaf
      password : abc
